trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:

# Step 1: Install Node.js
- task: NodeTool@0
  displayName: 'Install Node.js'
  inputs:
    versionSpec: '20.x'

# Step 2: Install packages
- task: Npm@1
  displayName: 'npm install'
  inputs:
    command: 'install'
    workingDir: '.'

# Step 3: Build Angular
- task: Npm@1
  displayName: 'Angular Build Production'
  inputs:
    command: 'custom'
    workingDir: '.'
    customCommand: 'run build -- --configuration production --no-progress'

# Step 4: Deploy to Azure Static Web App
- task: AzureStaticWebApp@0
  displayName: 'Deploy to Static Web App'
  inputs:
    app_location: '/'
    output_location: 'dist/exam-evaluate-portal'
    skip_api_build: true
  env:
    azure_static_web_apps_api_token: 'c132a7812967f63254ce0b198749fd868aa30457b3ba015c10d68b10a2412c4102-e63e174d-0824-4cbc-9f4f-f166558b712100031270f0acc800'