trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:

# Step 1: Install Node.js
- task: NodeTool@0
  displayName: 'Install Node.js'
  inputs:
    versionSpec: '20.x'

# Step 2: Install packages
- task: Npm@1
  displayName: 'npm install'
  inputs:
    command: 'install'
    workingDir: '.'

# Step 3: Build Angular
- task: Npm@1
  displayName: 'Angular Build Production'
  inputs:
    command: 'custom'
    workingDir: '.'
    customCommand: 'run build -- --configuration production'

# Step 4: Deploy to Azure Static Web App
- task: AzureStaticWebApp@0
  displayName: 'Deploy to Static Web App'
  inputs:
    app_location: '/'
    output_location: 'dist/exam-evaluate-portal'
    skip_api_build: true
  env:
    azure_static_web_apps_api_token: $(5633698d9db093a974a825fdf828eddf5385f1080e05d25c71d38fbc186a9b3e02-8a55ae9d-2c90-4d31-8d21-e8e39119e48500031270f0acc800)